const main = async () => {
	console.log(`Database has been seeded. ðŸŒ±`)
}

main().catch((err) => {
	console.warn("Error while generating seed: \n", err)
})
